//go:build ignore

// gen_timezones reads the IANA timezone database bundled with the Go toolchain
// and writes timezones_gen.go to the current directory.
//
// Run with: go generate (see timezones_gen.go header)
package main

import (
	"archive/zip"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"sort"
	"strings"
)

func main() {
	zipPath := filepath.Join(runtime.GOROOT(), "lib", "time", "zoneinfo.zip")
	r, err := zip.OpenReader(zipPath)
	if err != nil {
		log.Fatalf("open zoneinfo.zip: %v", err)
	}
	defer r.Close()

	// Only include zones under these canonical IANA continental prefixes.
	// This excludes legacy aliases (US/Eastern, Canada/Eastern, Brazil/East, etc.)
	// and the confusing Etc/GMT±N inverted-sign zones.
	canonical := []string{
		"Africa/", "America/", "Antarctica/", "Arctic/", "Asia/",
		"Atlantic/", "Australia/", "Europe/", "Indian/", "Pacific/",
	}

	var zones []string
	for _, f := range r.File {
		if f.FileInfo().IsDir() {
			continue
		}
		name := f.Name
		for _, prefix := range canonical {
			if strings.HasPrefix(name, prefix) {
				zones = append(zones, name)
				break
			}
		}
	}

	// Always include UTC as the neutral default.
	if !slices.Contains(zones, "UTC") {
		zones = append(zones, "UTC")
	}

	sort.Strings(zones)

	out, err := os.Create("timezones_gen.go")
	if err != nil {
		log.Fatal(err)
	}
	defer out.Close()

	fmt.Fprintln(out, "// Code generated by gen_timezones.go; DO NOT EDIT.")
	fmt.Fprintln(out, "// Regenerate with: go generate ./internal/handler/")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "package handler")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "// allTimezones is the full list of IANA timezone names from the Go toolchain's")
	fmt.Fprintln(out, "// embedded tzdata, excluding abbreviations (EST, MST) and inverted Etc/GMT± zones.")
	fmt.Fprintln(out, "var allTimezones = []string{")
	for _, z := range zones {
		fmt.Fprintf(out, "\t%q,\n", z)
	}
	fmt.Fprintln(out, "}")
}
